# Generated by Django 4.1.1 on 2023-06-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 15, 17, 15, 33328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 15, 17, 15, 33328, tzinfo=datetime.timezone.utc)),
        ),
    ]
